apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: ab
  replicas: 2
  template:
    metadata:
      labels:
        app: ab
    spec:
      containers:
      - name: myapp
        image: nginx

        ports:
        - containerPort: 3000
