apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: k8-demo
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 3000
